[project]
name = "nummet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.1",
    "seaborn>=0.13.2",
    "xarray>=2026.1.0",
]
